### ISSUE TITLE
Upgrade to .NET Core 3.1.

### ISSUE THREAD

**Issue by serpent5** [serpent5/Serpent5.Extensions.Configuration#1]
The current version is for .NET Core 2.2, but .NET Core 3.1 is here and it's LTS. It makes sense to make this project work with that, too.

On the off chance that anyone out there is actually using this thing, let me know here and I'll do the work for this.

**Comment by UncleDave** [comment]
Hi I'm using this, thanks for the Lib bro.

**Comment by serpent5** [comment]
Done.
